name: Deploy Stg Prod

run-name: Deploy test-envs stg → prod from ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
  workflow_dispatch:

jobs:
  deploy-stg:
    name: Deploy to stg
    permissions:
      contents: write
    uses: ./.github/workflows/_deploy_app.yml
    with:
      appName: test-envs
      lifecycle: stg

  deploy-prod:
    name: Deploy to prod
    needs: deploy-stg
    permissions:
      contents: write
    uses: ./.github/workflows/_deploy_app.yml
    with:
      appName: test-envs
      lifecycle: prod
