name: Deploy Dev Test

run-name: Deploy test-envs dev → test on ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to dev
    permissions:
      contents: write
    uses: ./.github/workflows/_deploy_app.yml
    with:
      appName: test-envs
      lifecycle: dev

  deploy-test:
    name: Deploy to test
    needs: deploy-dev
    permissions:
      contents: write
    uses: ./.github/workflows/_deploy_app.yml
    with:
      appName: test-envs
      lifecycle: test
